### ISSUE TITLE
version controlling table state

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_CityIO_Backend#20]
This has been in topic since we started, and has had iterations in the past. This post is a memorandum to show how "Git" copes with different file states.

image below is a normal way of thinking about deltas.
![](https://git-scm.com/book/en/v2/images/deltas.png)

while the one below is how Git handles it.
![](https://git-scm.com/book/en/v2/images/snapshots.png)

The good thing is that any given state,
you get a complete version of what you want. The question is in our case, what is the equivalent of a file in git? is it one cell in a grid? or is it a grid?

**Comment by RELNO** [comment]
@yasushisakai  that goes back to our discussion about the size of each file/version. If we quarry 2mb in each version, both server and endpoints would suffer from that, which makes your option A more relevant. But in terms of simplicity, getting the entire table/grid in any given time is easier at option B.

**Comment by popabczhang** [comment]
I will say let's start with option B first, until we hit the limit.
