### ISSUE TITLE
New Table JSON Format Example

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#25]
Set up one dummy table [maybe dynamic] in the API so other developper  can start working on converting their parsers. 

Format here 
https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Format

**Comment by popabczhang** [comment]
the json composer is updated to the new format in [CS_Rhino_Grasshopper_Template](https://github.com/CityScope/CS_Rhino_Grasshopper_Template). 

You can see the latest uploaded data in CityI/O server table name: [citymatrix_template](https://cityio.media.mit.edu/api/table/citymatrix_template). 
`https://cityio.media.mit.edu/api/table/citymatrix_template`

**Comment by agrignard** [comment]
@popabczhang good job however just keep in mind that the new format is not yet totally finished. 

We didn't converge yet so let's try to do everything in the right order (especially regarding this issue https://github.com/CityScope/CS_CityIO_Backend/issues/26)

If you are in a rush I propose you to organize a meeting so that we can all agree on the final format and then we let @yasushisakai producing the right one and update the doc

**Comment by popabczhang** [comment]
Sure, I aware of it. I will update the repo when it converge. I just wanted to finish most portion of the work using this weekend. I will organize a meeting with Yasushi.

**Comment by yasushisakai** [comment]
will have this after 02/06/2018

**Comment by yasushisakai** [comment]
prepared to be run on the name of fake_table ```https://cityio.media.mit.edu/api/table/fake_table```. Updates every minute

**Comment by yasushisakai** [comment]
virtual_table then
