### ISSUE TITLE
"x_ext" "y_ext" instead of "col" "row"

### ISSUE THREAD

**Issue by popabczhang** [CityScope/CS_CityIO_Backend#26]
In "header", "spatial", I suggest to use "x_ext" and "y_ext" instead of "col" and "row" to reduce confusion.  
"x_ext" means extent in x direction, "y_ext" means extent in y direction.

**Comment by agrignard** [comment]
col and row means the number of row and col. It is quiet clear for everyone and it follows as well and already established standard format http://www.fountainware.com/compass/HTML_Help/DEM_Reader/deminfo.htm

To be really coherent we should  call it ```rows```  and ```cols```

**Comment by agrignard** [comment]
and to follow thie format ```rotation``` should be call ```angle```

**Comment by agrignard** [comment]
@yasushisakai I let you make the modification in the wiki before to close this issue

**Comment by agrignard** [comment]
FYI we are not the only one to try to define our own format
http://www.reliefshading.com/analytical/dem-file-formats/

**Comment by popabczhang** [comment]
I agree we should follow the most popular existing standard. To converge on it, I propose: 

````
ncols         16
nrows         16
xulcorner     -71.087264
yulcorner     42.360357
angle         0.0
cellsize      10
````

**Comment by yasushisakai** [comment]
+1 on using existing formats.

**Comment by yasushisakai** [comment]
```
ncols, nrows, latitude, longitude, angle, cellSize
```
