### ISSUE TITLE
[Format] angle consistancy

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_CityIO_Backend#28]
In the header, it is declared to use radians in ```rotation```, while each cell has rotation in degrees. Which do we want? (assuming both the direction is in clockwise)

**Comment by popabczhang** [comment]
Currently, for a lego piece in a grid system, we only have four different rotation values: 0 degree, 90 degree, 180 degree, and 270 degree. So I suggest to use integer "0, 1, 2, 3" instead, and have a mapping method in the header. 

```
"mapping": {
      "rotation":{"0":"0 degree", "1":"90 degree conterclockwise", "2":"90 degree conterclockwise", "3":"90 degree conterclockwise"} // example, not requried
}
```

**Comment by popabczhang** [comment]
I am okay with either degree or radians. Agree that it needs to unify. I am okay with either clockwise or conterclockwise as well.

**Comment by agrignard** [comment]
@yasushisakai what do you mean by in the header? which one

I think it's just a question of convention we don't need to have a mapping as soon as we agree on the convention. 

However I think it's more precise to use  degree (especially for our case). 0,90,180 and 270 are  int. Whereas how do you define PI? We will have some problem of precision here depending on the software used.

**Comment by popabczhang** [comment]
agree on the difficulty in defining Pi in different software. So we should use degree as well in 'angle' ? 
Let converge in tomorrow's meeting.

**Comment by yasushisakai** [comment]
we use degrees, counter clock wise
