### ISSUE TITLE
"type", "height", "rotation" instead of "rotation", "type", "height"

### ISSUE THREAD

**Issue by popabczhang** [CityScope/CS_CityIO_Backend#31]
Minor detail, I feel "type" is way more important than "rotation" in each cell. Can we have it `"type", "height", "rotation"` instead of `"rotation", "type", "height"`? 

If so, it would be great to change the virtual_table as well. 
Just need to change the order of following code in `CS_CityIO_Backend/examples/fake-table/Header.py`: 
```
cell.append(choice(Header.rotations))
cell.append(randrange(10))
cell.append(self.mapping.randtype())
```

**Comment by yasushisakai** [comment]
I'm ok with it! Is this managable? @agrignard @RELNO

**Comment by agrignard** [comment]
yep, ok for me too

**Comment by yasushisakai** [comment]
cool, will be rolling out soon

**Comment by yasushisakai** [comment]
rolled out in  ef27f03. Now on air. Please change accordingly.
@RELNO @agrignard @popabczhang

**Comment by popabczhang** [comment]
Great! Thank you very much, Yasushi! 
The Grasshopper JSON sender in template repo was updated accordingly already.
