### ISSUE TITLE
Change the location of the table 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#35]
When reaching https://cityio.media.mit.edu/ the table or not exactly well localised.

Right now we don't have the lat and long in most of them I guess (as they don't follow all the last spec) but it would be nice to display them at the right location (maybe with a simpel manual offset)

**Comment by RELNO** [comment]
@agrignard I guess this is a question for the front-end [other repo], but in general -- I'll enroll a new version of the frontend as soon as we have the new data format up and running for at least a couple of tables [Tongji, helsinki]. 

As the rest that will not migrate to the new format will be indeed geolocated manually.

**Comment by RELNO** [comment]
@agrignard  also, can you point out a table [besides BRT] who's not in its right location?

**Comment by agrignard** [comment]
Ok indeed when I zoom they are at the right location, it's just on the default view there is a big offset but it might be due to the way you display it here it seems that we have a table in Algeria, one in Ukrainia and one in Philippines 
<img width="846" alt="screen shot 2018-03-13 at 16 44 20" src="https://user-images.githubusercontent.com/3928502/37368903-eee43a90-26dd-11e8-9c97-ff305540f40a.png">

**Comment by RELNO** [comment]
A. True, icon markers are now calculating location from top left corner, should have it in middle -- I'll open an issue for this in frontend
B. It's about time we'll have tables in Algeria, Ukrainia and Philippines
