### ISSUE TITLE
Declare NO-CORS in client options to avoid CORS error in FETCH api

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO_Backend#37]
[See `Fetch` POST example](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) :
```
postData('http://example.com/answer', {answer: 42})
  .then(data => console.log(data)) // JSON from `response.json()` call
  .catch(error => console.error(error))

function postData(url, data) {
  // Default options are marked with *
  return fetch(url, {
    body: JSON.stringify(data), // must match 'Content-Type' header
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, same-origin, *omit
    headers: {
      'user-agent': 'Mozilla/4.0 MDN Example',
      'content-type': 'application/json'
    },
    method: 'POST', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, cors, *same-origin
    redirect: 'follow', // manual, *follow, error
    referrer: 'no-referrer', // *client, no-referrer
  })
  .then(response => response.json()) // parses response to JSON
}
```

**Comment by RELNO** [comment]
Revisiting this, now with the new server: 

when trying `no-cors` mode:
<img width="544" alt="screen shot 2018-06-14 at 08 54 28" src="https://user-images.githubusercontent.com/14296774/41413324-bfae82a0-6fb0-11e8-9a04-4400bb759a4f.png">
get:
<img width="648" alt="screen shot 2018-06-14 at 08 54 40" src="https://user-images.githubusercontent.com/14296774/41413349-d1991e12-6fb0-11e8-81cc-d81d378d3ec0.png">

When instead not using any mode:
<img width="446" alt="screen shot 2018-06-14 at 08 54 55" src="https://user-images.githubusercontent.com/14296774/41413367-def6b6fa-6fb0-11e8-8228-3b8137454800.png">

Getting `CORS` error:
<img width="660" alt="screen shot 2018-06-14 at 08 55 01" src="https://user-images.githubusercontent.com/14296774/41413380-e8627616-6fb0-11e8-8ea5-668c7f5c2ab3.png">

If not a security issue, can you add CORS headers to GET/POST reqs.? 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by yasushisakai** [comment]
thanks for the feedback, this will be in the list to check in the next version, do you think this will affect the other clients like GAMA?

**Comment by RELNO** [comment]
@yasushisakai Thanks!  - I think it should not. If any `GET/POST` requests currently handled by other end-users [gama, etc] is done over some sort of HTTP req. that does not yield this issue [similar to the one working well for JS - AJSX calls]. 
Thus, adding some language to CityIO server's `header` should not be of their concern - e.g it's simply making an already open door a bit wider.

**Comment by RELNO** [comment]
I'm escalating it to bug since now both `FEATCH` and `AJAX` post/get calls are close to be rejected: 

<img width="477" alt="screen shot 2018-06-19 at 11 58 57" src="https://user-images.githubusercontent.com/14296774/41609241-534dc0d8-73b8-11e8-8483-075c733c1ad8.png">

https://www.chromestatus.com/feature/5629709824032768
https://stackoverflow.com/questions/50873764/cross-origin-read-blocking-corb

**Comment by yasushisakai** [comment]
seems it has resolved? for @RELNO 's purposes, scheduled to be reopened when switching to the go version.

**Comment by RELNO** [comment]
not resolved, but yeah, let's wait till we GO.. ;)

**Comment by yasushisakai** [comment]
ok, I'm now allowing, 

- Origin: *
- Headers: Origin, ContentType, Accept,
- Methods: GET, POST

I don't think I can be permissive than this...
For development, I've read you should use a no-cors plugin,
which I see both fore Chrome and Firefox.

could you check this out, jsonp path seems to be quite a detour. (and seems old?)

**Comment by RELNO** [comment]
fixed on https://github.com/CityScope/CS_CityIO_Backend/issues/43
