### ISSUE TITLE
Please update cityIO frontend to this tag

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO_Backend#38]
https://github.com/CityScope/CS_CityIO_Frontend/releases/tag/mark_1_Zuckerberg

**Comment by RELNO** [comment]
Don't know if you've started working on it, but I'm getting this now:

<img width="537" alt="screen shot 2018-05-13 at 13 45 55" src="https://user-images.githubusercontent.com/14296774/39970113-0a073812-56b4-11e8-9432-c1491e2f0c45.png">

**Comment by RELNO** [comment]
added pull https://github.com/CityScope/CS_CityIO_Backend/pull/39

**Comment by yasushisakai** [comment]
approved #39, but now redirecting to github pages
