### ISSUE TITLE
What about a clear entry point to the current official template?  

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#41]
It's kidn of hard to find the official template of generic table from the documentation, maybe it could be in the README directly?

**Comment by yasushisakai** [comment]
added a direct link to the data template, will this do?

**Comment by agrignard** [comment]
Yep also I was maybe thinking about a clear entry point to show one of the table (I mean the json file). BTW do we have a kind of "'"official""" one?

**Comment by agrignard** [comment]
We use to have a virtual table, is it possible to have it back? It could be the template that follows the version. Maybe we could think about a script that generate a virtual table in link with the version

**Comment by yasushisakai** [comment]
updated read me to have direct link to virtual_table.

**Comment by agrignard** [comment]
What about having this table in the available one here?
http://cityscope.media.mit.edu/CS_CityIO_Frontend/

I don't see it
