### ISSUE TITLE
https://cityio.media.mit.edu/ down 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO_Backend#42]
`502 bad gateway`

**Comment by yasushisakai** [comment]
back on

**Comment by RELNO** [comment]
down again.

**Comment by yasushisakai** [comment]
let's see with the new server 🍵

**Comment by RELNO** [comment]
![image](https://user-images.githubusercontent.com/14296774/41499622-eacd0b72-7150-11e8-9b7b-9e1d50371d47.png)

Yap, again.

**Comment by RELNO** [comment]
back up apparently.
