### ISSUE TITLE
did I miss anything with the tables/list endpoint?

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_CityIO_Backend#43]

**Comment by RELNO** [comment]
yes: 
<img width="338" alt="screen shot 2018-06-23 at 21 08 23" src="https://user-images.githubusercontent.com/14296774/41814917-97450016-7729-11e8-8a0f-1d6c88a44fb3.png">

**Comment by yasushisakai** [comment]
done?

**Comment by yasushisakai** [comment]
200 is a success code though...

**Comment by RELNO** [comment]
Not sure if relevant, but there was a time we had switched to     `dataType: "JSONP",`, could this be relevant ?

**Comment by RELNO** [comment]
<img width="662" alt="screen shot 2018-06-23 at 21 31 23" src="https://user-images.githubusercontent.com/14296774/41815031-d01d49b8-772c-11e8-9263-aabfc7c5d821.png">


<img width="452" alt="screen shot 2018-06-23 at 21 31 55" src="https://user-images.githubusercontent.com/14296774/41815034-e15c9ec2-772c-11e8-90b8-c778e4c9e611.png">

**Comment by yasushisakai** [comment]
I sniff this is relavant to #37 
jsonp was one method for allowing cross origin.

https://en.wikipedia.org/wiki/JSONP

**Comment by RELNO** [comment]
Right, and that +  Ajax was working[ish] till now..

**Comment by yasushisakai** [comment]
can you try plain json?

**Comment by RELNO** [comment]
Plain json get CORS issue: 
```Failed to load https://cityio.media.mit.edu/api/tables/list: The 'Access-Control-Allow-Origin' header contains the invalid value ''. Origin 'http://localhost:1234' is therefore not allowed access.```

**Comment by yasushisakai** [comment]
could you try pushing that to productoin, just wanted to know if it's kicking you out because of localhost, I've allowed few domains and modified headers.

**Comment by RELNO** [comment]
Just did, no GO.
There is one more thing: the CS org. is now directed from http://cityscope.media.mit.edu/
could this have an a effect? I've actually dist for both domains [github pages and ML] and had the same issue, but maybe in your end it's different?

**Comment by RELNO** [comment]
@yasushisakai for fun I've tried Axios, still the same. Is it possible to try `Access-Control-Allow-Origin = *`?

**Comment by yasushisakai** [comment]
I'll try that ```*```

**Comment by RELNO** [comment]
Ok, working now [for recalling later, this is the ajax call]

```
async function getCityIO(cityIOurl) {
  // GET method
  return $.ajax({
    url: cityIOurl,
    dataType: "JSON",
    callback: "jsonData",
    type: "GET",
    success: function(d) {
      return d;
    },
    // or error
    error: function(e) {
      console.log(e);

      console.log("GET error: " + e.status.toString());
      infoDiv("GET error: " + e.status.toString());
    }
  });
}

```

**Comment by agrignard** [comment]
This is what I get with 
````
https://cityio.media.mit.edu/api/tables/list
`````

I have this
`````
["https://cityio.media.mit.edu/api/table/citymatrix_volpe","https://cityio.media.mit.edu/api/table/virtual_table","https://cityio.media.mit.edu/api/table/CityScopeJS","https://cityio.media.mit.edu/api/table/TEST"]
``````

We use to have just the name of the table no? Why pushing everytime the entire url? Which ias always the same?

**Comment by RELNO** [comment]
@agrignard no, we used to have full addresses. Let's not change these things every couple of days. This requires refactoring 4 repos each time.

**Comment by agrignard** [comment]
first time I see it (i guess you and @yasushisakai changed it recently)  anyway...
