### ISSUE TITLE
type of the key in mapping types

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#44]
@yasushisakai 

For this dictionary of the mapping type we didn't really precise the type in the dictionnary 
https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Format#mapping-dictionary

e.g 
`````
{"0"::"R"}
`````
but also it could be

````
{0::"R"}
`````

I think it makes sense to have int::string right? or int::int but at least the key should be an int as this is what we send in the grid.

This is a bit related to this issue
https://github.com/CityScope/CS_cityscopeJS/issues/7

**Comment by yasushisakai** [comment]
yes, I agree it should be a numerical type, I guess the size of the type (char, int, int64) is up to practicality. Yet, **I think JSON specs the key values should be strings...** (correct me if I'm wrong)

I guess historically, people wanted something like this:
```{"-99": "none", "0": "road", "1":"park", "100": "residence", "101": residence_low_income}```
due to the fact we had to manually agree in types,

But now we have a self-explanatory api (it's each tables responsibility), we could just do with an list
```["none", "road", "park", "residence", "residence_low_income"]```

what about it, senders??
@RELNO @popabczhang

**Comment by RELNO** [comment]
@yasushisakai not an expert on JSON structs, but would prefer avoiding conversion to `int` every-time I send/receive

**Comment by agrignard** [comment]
@yasushisakai for this proposal
````
["none", "road", "park", "residence", "residence_low_income"]
`````

why not but here we would assume that the id are from 0 to N, with the dictionnary we can have non continuous id 

I am not against what you propose it's just a question of standard, I think we can keep this dictionary for 2.1.0 as it is documented like that in many places

**Comment by RELNO** [comment]
@yasushisakai -  @agrignard this is true, and there is another issue which supports "1":"type" -- there might [and will] be `-1` types which will fall out of a normal list.

**Comment by yasushisakai** [comment]
Yes, this will increment versions number. (I think its a change that breaks backward compat. for strict type languages) so version 3.

I guess JSON Objects( = dictionary) must be string by the JSON specification.
As long was we are sticking with JSON, we cant do about having key values other than strings.

**Comment by yasushisakai** [comment]
the current type implies the following is valid
```
{
"":"nothing here", 
"undefined": "",
"this is a type that contains a lot of rocks compressed together called asphalt and people step on them": "road",
}
```
I forsee first and second cases

**Comment by agrignard** [comment]
ok so I guess this issue can be closed. we put a string in the key (maybe a small update in the wiki?)
