### ISSUE TITLE
Broken link for the virtual table

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#45]
This link doesn't work anymore https://cityio.media.mit.edu/api/table/virtual_table

As it is link it different wiki page as the "official" valide table it can be nice to have it always

**Comment by yasushisakai** [comment]
back up

**Comment by RELNO** [comment]
as mentioned in https://github.com/CityScope/CS_CityIO_Backend/issues/49, table is offline.

**Comment by tuxun** [comment]
But: can a virtual table be online? i suggest assign this table type "archivable" and https://github.com/CityScope/CS_CityIO_Backend/issues/49#issuecomment-440228517

**Comment by RELNO** [comment]
on our to do list!

**Comment by agrignard** [comment]
close see issue #58
