### ISSUE TITLE
idea: client/services announcing themselves to backend

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_CityIO_Backend#54]
Hi, in the frontend, and in the legotizer there is a 'show this table as raw' button. I would like to see some others buttons here...
For example, somewhere a legotizer push a exampletable.json. somewhere else there is a CS_CityScopeJS_UI instance, a CSjs_WALK instance, and a CSjs_MOBO instance, you get the point. Wouldnt it be cool if the legotizer or the frontend could show automagically links to web view of the tools  (especially in the legotizer, i got this idea cause in this video https://www.youtube.com/watch?v=Z7v2clIaTKY&t=194s @RELNO  has a custom "opentable" link)

**Comment by RELNO** [comment]
Go ahead and implement it! I'll be happy to see PR's @ https://github.com/CityScope/CS_cityscopeJS or https://github.com/CityScope/CS_cityscopeJS_UI

Technically speaking, you might find that the differentiation between different CityScope tables makes it harder to have a every instance working with every front end.

**Comment by RELNO** [comment]
Closing, as this is not Backend related suggestion. Please add to https://github.com/CityScope/CS_cityscopeJS / UI

**Comment by tuxun** [comment]
well, i wanted to add smthing like api/table/name/services/list... in the API, returning a kind of: name, url, name, url, name, url
I don't want all instance able to work with each table, only those whose declared themselves.

That also could act as a safety, for example a undeclared legotizer could be blocked for make a table update. (why could a service update or remove a table if it is not declared to use it?)

**Comment by RELNO** [comment]
@tuxun I'm not sure I'm following: A CS table can have multiple inputs and outputs. You can, for ex., have a VR headset, a projection and twitter bot all reading from the same cityIO endpoint. Therefore I don't get the API idea -- if you lock service to a table, you force one to make a new service for each table?

**Comment by tuxun** [comment]
for outputs, no locking, its useless, i was thinking about multiples inputs issues (still speaking about locking). 
That could be useful for inputs, acting at least as a semaphore (how do you handle two legotizer speaking to one cityIO server with the same table at the moment?) one remove the update of another and vice versa?
but at first the point to announce service was just to make the frontend or any client able to show another link to another client if it exists. (making a guy debuging a service able to see another view of his table but with another service )

**Comment by RELNO** [comment]
> (how do you handle two legotizer speaking to one cityIO server with the same table at the moment?) one remove the update of another and vice versa?

Yes, they erase each other. Again, unless one has vandalizing intentions in mind, why would they try to overwrite a table in real time? 

> make the frontend or any client able to show another link to another client if it exists. 
Did you tried this?
https://cityscope.media.mit.edu/CS_CityScopeJS_UI/?CityScopeJS

Read thorugh it here: 
https://github.com/CityScope/CS_CityScopeJS_UI/blob/master/readme.md

**Comment by tuxun** [comment]
https://github.com/CityScope/CS_CityIO_Backend/issues/49
dont lock output, only input, there is no semaphore atm, leading to everyone testing your mit hosted legotizer updating table with default setting.json erase your real lego table data and making a mess at least a short moment if your are watching it :)

**Comment by tuxun** [comment]
i told you, just by mistake, i'm not a vandal, but i learn from my mistake, i guess im not alone! :D

**Comment by RELNO** [comment]
That's why none of the tables in IRL and in the examples are actually running the same name.. 
I'm still not sure I understand your idea of locking input, care to sketch a simple diagram?

**Comment by tuxun** [comment]
Please just clarify something: above you say multiple inputs are allowed at the moment? if a legotizer build a map then put a json on server, can a gama simulation also write it? what other apps could be input? 

NB: I'm happy to know i never erased someone else real work but only experiences like mines :)

**Comment by RELNO** [comment]
anyone who can do `POST` req to cityIO can write, JS, JAVA.. As said, a good workflow will include a unique name [in JSON settings file] for your POST, so cityIO can parse it as new poster. However, if we all send on the same name, we overwrite each other.  To this point, [and maybe that is not clear] the way a CityScope table read [`GET`] cityIO is on a short time interval of ~.5 sec. So, if you or me are overwriting each other, we'll see this messing up the table very very quickly. It's a tradeoff for sure, but one that opens up the server side to all, no email/password attached..

**Comment by tuxun** [comment]
that was just a  simple question for help me to answer to your question: if multiple input are intended in the future and by design, there is no reason to lock them to single service, but if we implement a service announcer, there is no reason it does not act a simple semaphore (if an input (server side) try to update an existing base, and its a legotizer and there is already a legotizer using this base at the moment, answer should be busy (use your legotizer with another tablename in your json!))
