### ISSUE TITLE
./boot.sh does not start sessions, bash commands do.

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO_Backend#57]
./boot file fails to properly start sessions 

## Process

1. Restart server

## Expected result

CityIO and MoCho services should run 

## Current result

NGINX error page, both services are off

## Current Fix

Running the session stratup through normal bash: 
```
cityio:CS_CityIO_Backend noyman$ sudo tmux new -d -s cityio '/Users/yasushi/code/go/bin/CS_CityIO_Backend'
cityio:CS_CityIO_Backend noyman$ sudo tmux new -d -s choiceModels '/Users/Shared/CS_choiceModels/runCM.sh'
```

## Permanent Fix 

Rethink service sequencing

**Comment by RELNO** [comment]
@yasushisakai the boot sh does not restart the server, can you advise?

**Comment by yasushisakai** [comment]
```boot.sh``` has been rewritten to trigger shared sessions

we can know see the tmux-session from different users by attaching via 
``` tmux -S /tmp/shared a -s cityio```
and 
``` tmux -S /tmp/shared a -s choiceModels```

the boot.sh reminds you how when you write it.
