### ISSUE TITLE
Wrong link to virtual table

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#58]
Broken link to point to a virtual table
https://cityio.media.mit.edu/api/table/virtual_table

**Comment by agrignard** [comment]
@RELNO @yasushisakai 
any update on this? to have at least a place to link to a table?

**Comment by agrignard** [comment]
It would be nice to have a virtual table generated as soon as the server is restart

**Comment by yasushisakai** [comment]
can I ask a useful template of a table? I'm thinking to hardcode it

**Comment by RELNO** [comment]
MoCho?

**Comment by RELNO** [comment]
https://cityio.media.mit.edu/api/table/virtual_table 
this table will run as long as necsys VM is alive. Ping cityIO @50ms with 25x25 grid of 5 types 
closing https://github.com/RELNO/CS_Modules/commit/4865bfa6fed326ebae2bc73c3c20ba3cd8affada

**Comment by agrignard** [comment]
https://github.com/CityScope/CS_CityIO_Backend/issues/70

**Comment by agrignard** [comment]
> can I ask a useful template of a table? I'm thinking to hardcode it

Can we agree to have a local reference version in this repo here:
https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/virtual_table.json

There is no guarantee that a url give the right version.

**Comment by RELNO** [comment]
https://github.com/RELNO/CS_Modules/commit/5be2f06a4d796ed7880ff5313952cc0032e0406a closes #70

**Comment by RELNO** [comment]
> Can we agree to have a local reference version in this repo here:
> https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/virtual_table.json

Two different purposes: the 'always-on' virtual table is for CSL to test changing designs without a table running. The static JSON link can be used as a static documentation reference.

Closing for now

**Comment by agrignard** [comment]
Working now.

It's important to keep a reference locally to test the example as there is no way to be sure that what is send to an url as it is send by a thrid app (as proved by this issue)
