### ISSUE TITLE
GrassBrook table format

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Backend#63]
In https://cityio.media.mit.edu/api/table/grasbrook
Is it possible to put the grid data as an array to be 2.1 compatible?
`````
[-1]
`````
instead of
`````
-1
`````
https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Format#block-array

**Comment by agrignard** [comment]
Maybe should be posted here?
https://github.com/CityScope/CS_CityScopeJS_Simulation

**Comment by RELNO** [comment]
It's an array:
`"grid":[-1,....0],`

I think `cityio_gama` actually follows V1 or something similar, where each grid cell held meta (rotation, etc).You might be referring to the scanner results of Cooper, in which we agreed to diverged from  cityIO format for simplicity.  
See https://cityio.media.mit.edu/api/table/cityscopejs_walk or MoCho for another example of same format running.

**Comment by RELNO** [comment]
I'm closing for now, please open again in https://github.com/CityScope/CS_Scanner_Python if needed.

**Comment by agrignard** [comment]
cityio_gama is in the 2.1 format 1.0 is now only used by CityMatrixVolpe. 

I am trying to unify the format which is in theory used by different project but not yet in practice.

If you compare with virtualtable It should be an array of array according to our format. 
If not there is no way to have a generic loader. Something that knows the size of the array according to what is populated in mapping (which is also incoherent in grassbrook table)

So is it possible to have this in order to have a generic read/write format

**Comment by agrignard** [comment]
Also according to https://github.com/CityScope/CS_Scanner_Python#scan-results we need an array

**Comment by agrignard** [comment]
So it seems that there is the same problem in 
https://cityio.media.mit.edu/api/table/cityscopejs_walk

We might need to discuss it all together however according to the spec described in 2.1 we need an array of array (even if there is only one element in the array)
https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/virtual_table.json

**Comment by RELNO** [comment]
> Also according to https://github.com/CityScope/CS_Scanner_Python#scan-results we need an array of array

That's what I meant by Cooper's format -- these documentations are out of date. 
As for the common v2.1 -- there is no mention in docs for array of array. Actually I remember us talking about keeping the `grid` field clean [which is NOT the case in v1] and populate attributes in `objects` or `mapping`. 

Yes, let's talk this (again ;)) -- It might also be a good opportunity for V2019..

**Comment by agrignard** [comment]
Speaking about 2.1 there is no way yet to validate it (every project in a standalone for now). 

We should have a generic reader (ideally in different languages as what we have in the ```èxamples````folder that can deal with any compatible 2.1 format. We are almost there for some language  but typically this array of array is one of the reason why it's not there working generically.

**Comment by agrignard** [comment]
see #64
