### ISSUE TITLE
Hashed id doesn't function correctly with new API 

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_CityIO_Backend#79]
The 'id' field on cityIO used to be helpful as I could tell when the grid had been updated before making updates using eg. CS_choicemodels.
However although I think the new 'module' structure is very useful, the id field can no longer work in this way so I think we should think about a new way of providing this information.

For example, previously the workflow for updating model estimates in response to grid changes was something like:

while True:
    if cityio['id']==last_id
        do nothing
    else:
        update_model_estimates()
    sleep(1)

However, with the new structure, each time the grid data changes, my updated model estimates are being Posted to a field in the same cityIO json. When this happens the hashed id will change again. Therefore, the next if statement will also be False and the cycle will continue (unless the model estimates are deterministic in which case there will be just one unnecessary calculation and update). 

Perhaps, we need to have separate hashed ids for each module (grid, mobility_service, noise) etc. so that each module can check if a particular module has changed rather than checking if the json as a whole has changed. It may make sense for each module to calculate their own hash id every time and include it with every Post.

**Comment by doorleyr** [comment]
Actually, looking at this again, it looks like there is a hashed id for each module but only the last updated one remains.
eg. if I post data to mocho/trips, then the meta field contains a "trips" field.
However, if I then post to mocho/site_geojson, then the meta field contains "site_geojson" but not "trips"

**Comment by yasushisakai** [comment]
> However, if I then post to mocho/site_geojson, then the meta field contains "site_geojson" but not "trips"

I'll look into this. Thanks for putting this up @doorleyr .

and yes, I knew this was one complication and haven't have the change to 
discuss.

One edge case example I wasn't sure was..
if someone sends an empty array through the
module update  `api/table/update/{sometable}/grid`

meta will contain a hash for `grid`, but as soon as the table updates itself
we will have the wrong meta id for `grid`

This is a stupid example, but I see modules clashing when they start to 
depend on each other.

**Comment by yasushisakai** [comment]
d8eabcfb3931418701f48263c92bc43ba8fd24ae
has now field called `meta/hashes` that is lists the hash values of data chunks under the root.
